name: quickgui
adopt-info: quickgui
summary: a Flutter frontend for (quickget)[https://github.com/wimpysworld/quickget]
description: |
  The app is a frontend to quickget.
grade: stable
confinement: classic
base: core20

architectures:
  - build-on: amd64

apps:
  quickgui:
    command: bin/quickgui
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      LIVE_RUN: 1
      LOG_LEVEL: debug

parts:
  quickgui-deps:
    plugin: nil
    stage-packages:
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libepoxy0
      - libgtk-3-0
      - libpango-1.0-0
      - libpangocairo-1.0-0

  quickgui:
    source: .
    source-type: git
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(cat pubspec.yaml | grep '^version: ' | cut -c 10- | sed 's/+/-/')"
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      flutter channel stable
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/x64/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
    build-snaps:
      - flutter/latest/stable
    after:
      - quickgui-deps
